### ISSUE TITLE
Required association not working with gradual loading

### ISSUE THREAD

**Issue by Tumetsu** [bredikhin/barrels#31]
[I already posted this on Stackoverflow](http://stackoverflow.com/questions/31804400/sailsjs-barrels-fixtures-required-associations) but decided to open issue here too.

I have following fixtures defined:
```
Project.json
[
    {
        "name": "TestProject",
        "integrations": 1
    },
    {
        "name": "TestProjectWithPeople",
        "integrations": 2,
        "projectLeads": [2],
        "members": [3]
    }

]
```

Activity.json
```
[
    {
        "project": 1,
        "content": {
            "text": "Just random content in JSON format 1"
        },
        "source": "Some other service",
        "userName": "Test user name",
        "activityType": "OldestActivity",
        "url": "http://www.example.com",
        "priority": 0
    },
    {
        "project": 1,
        "content": {
            "text": "Just random content in JSON format 2"
        },
        "source": "Some other service 2",
        "userName": "Another test user",
        "activityType": "Test2",
        "url": "http://www.example.com",
        "priority": 1
    },
    {
        "project": 1,
        "content": {
            "text": "Just random content in JSON format 3"
        },
        "source": "Some other service 2",
        "userName": "Another test user",
        "activityType": "Test2",
        "url": "http://www.example.com",
        "priority": 1
    }
]
```

The Activity model has required association to Project. After reading readme of Barrels I wrote the following code:
```javascript
loadFixtures: function() {
        return new Promise(function (resolve) {
            var barrels = new Barrels(process.cwd() + '/test/fixtures');
            barrels.populate(['project', 'integrations', 'user'], function(err) {
                barrels.populate(['activity'], function(err) {
                    console.log(err)
                    resolve();
                });
            });
        });
}
```

I keep getting validation error from second populate:

```
Invalid attributes sent to Activity:
 • project
   • "required" validation rule failed for input: null
```

What is the problem here? I tried switching off auto-association and it "works" meaning that it sets just bare numbers as association which works if they really represent correct model in association, but that seems to be fragile and will break if I ever use another test db other than sails-disk.

**Comment by CodeOtter** [comment]
I got this exact same problem, so when I turned off autoAssociations, I get the following error:

```Error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Error updating a record.```

This error is being raised from ```barrels/index.js:168:14```

**Comment by vcardins** [comment]
+1 - Same exact problem.

**Comment by bredikhin** [comment]
If anyone has a repository with some specific code where Barrels misbehave, I can take a look. And, of course, pull requests are welcome.

**Comment by Tumetsu** [comment]
I whipped up failing test cases to demonstrate the problem but unfortunately they are on computer I can't access atm. I see if I can redo it this weekend and make a fork. 

Anyway it is quite easy to demonstrate. Just add a required association field to a model and it will not work as expected even with gradual loading.

**Comment by YannBertrand** [comment]
You can take a look at the issue on [this projet](https://github.com/FriendsBet/API/tree/develop) (in the develop branch)

**Comment by bredikhin** [comment]
@YannBertrand Sorry if it's a bit late, but I finally got some time to look into the issue you guys are having. So, a Mongo collection named `group` is not a good idea, see http://stackoverflow.com/questions/16982849/how-to-remove-collection-named-group, for example. Basically, adding `tableName: 'grp',` or something like that to your model object fixes the population issue, although you have some tests failing. Anyway, I hope it helps. ;)

**Comment by Tumetsu** [comment]
Sorry for being late with this but I finally remembered and got to my pc with the demo I created earlier. I created a fork with new branch which includes couple new tests and fixtures to demonstrate the problem I had with required associations:

https://github.com/Tumetsu/barrels/tree/associationProblemDemo

**Comment by mattcodez** [comment]
I had the same issue but was able to resolve by disabling auto association on both levels of `populate()`.

**Comment by Tumetsu** [comment]
Do you repopulate your db in-between tests?

If I remember correctly when I reset db in between tests, the repopulation assigned new id:s for each model, so if you write association something like:
"product": 2, it will work only on first run when the product actually has id of 2. On next run the id might be something else (lets say 5). At least thats how I understand how the autoassociation works. This is the reason I'm really wary of disabling it.

Of course it doesn't matter as much if you populate the db only at the beginning of the test suite.

**Comment by stebl** [comment]
@Tumetsu , yes I've seen that behavior with sails before, and I believe that behavior is what allows barrels to work with required associations when autoAssociations are disabled.

You can track it down to [line 147 here](https://github.com/bredikhin/barrels/blob/master/index.js#L147).  With auto associations, the model is created with 0 associations, which breaks sails' validation step for required models.  If you turn it off, barrels will leave the associations in.  Sails defaults to creating id's 1, 2, 3... etc.  In some (most?) cases, the json ids for associations match the primary keys in sails, and sails will accept the association during creation.  In our case, we use uuids, so they never match.  Repopulating the db between tests should also fail, but I haven't tested.

More interesting, is it seems to me that autoAssociations with required associations should never work. Since the associations are stripped before creation and added after-the fact, sails should never allow it to pass validation.  

I have some workarounds...
1. Get rid of the required association.  Potentially undesirable for other reasons, but it works. 
2. Populate without auto and abuse sails id creation to let associations go through.
3. Populate without auto, specify "id" fields in the required model, and reference those ids in the model that has the requirement.  

I can't guarantee I'll have time to fix and PR this, but I'm going to tinker with it and try to find a better solution.

**Comment by bredikhin** [comment]
[v1.6.0](https://github.com/bredikhin/barrels/releases/tag/v1.6.0) should resolve this.

**Comment by markmssd** [comment]
Heads up!

I had the exam same problem. Now I tried to update to v1.6.0, but it crashes my Sails app:
```
Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/barrels/index.js:167
                item[alias] = that.idMap[associatedModelName][item[alias] - 1];
                                                             ^

TypeError: Cannot read property '0' of undefined
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/barrels/index.js:167:62
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/async/lib/async.js:209:22)
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/barrels/index.js:147:15
    at wrapper (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/destroy.js:123:11
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:263:32
    at /Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at bound.<anonymous> (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/Users/xxx/dev/PowerLearners/WebApp/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:136:10)
8 Nov 18:41:23 - [nodemon] app crashed - waiting for file changes before starting...
```

It used to work with v1.5.0...
Any advice?

**Comment by bredikhin** [comment]
@markmssd thanks for the heads-up, can you try with [v1.6.1](https://github.com/bredikhin/barrels/releases/tag/v1.6.1)?

**Comment by markmssd** [comment]
Alright I just tried, it's still failing but with the intended thrown error:
```
Error: Please provide a loading order acceptable for required associations
```
I thought that by passing the third argument as 'false' in
```
barrels.populate(fixtures, next, false);
```
would ignore the association order? Or maybe I misunderstand that argument?

**Comment by bredikhin** [comment]
No, you got it right. However, as it turned out, we can't skip the associations that are marked as required, so these are being handled based on the assumption that the corresponding fixtures are being loaded before they get required, i.e. models ordered in a specific way, https://github.com/bredikhin/barrels#required-associations. If you think about it, it makes sense.

**Comment by markmssd** [comment]
Indeed it makes a lot of sense! I'm now populating them in the correct order and it works perfectly.

Very good support,
Thanks!

**Comment by marnusw** [comment]
Is it just me or should the collections be loaded with `eachSeries` [here](https://github.com/bredikhin/barrels/blob/0ade7fc11bed6b31e6572ec2018e0a2f6a2333c6/index.js#L128)? 

I'm using `v1.6.2` and I've got the loading order set up correctly, but I still get the error:

```
Invalid attributes sent to Passport:
 • user
   • "required" validation rule failed for input: null
```

I'm using `sails-disk` at the moment. I wonder if some of the other adapters don't serialize the loading internally. That might explain why it (apparently?) works with Mongo DB but in my case.

If I change that line to use `eachSeries` everything works as expected.

**Comment by stebl** [comment]
Here's my understanding of it.  If your 'user' has a required 'something'
and you try and load them at the same time, then that should create a race
condition for the requirement.  If you change that to eachSeries, you
should get consistent behavior.  On the other hand, it may still not do
what you want.  If 'something' gets loaded before 'user', it will work, but
if 'user' gets loaded before 'something' then you're in the same spot (I
think the order is alphabetical in the folder, but I'm not sure).  Certain
adapters may handle this better than others, but I think the validations
are adapter-independent?

On Tue, Dec 29, 2015 at 4:20 AM, Marnus Weststrate <notifications@github.com

**Comment by marnusw** [comment]
I think you're right @stebl, that is how I understand it as well. If left to its own devices `barrels` will probably load the fixtures in alphabetical order and odds are that won't be the correct order. In that case I think one would see the `"Please provide a loading order acceptable for required associations"` error message.

In the case I'm describing I am specifying the order in which the fixtures should be loaded, and `users` are loaded before `passports`:

```javascript
var loadOrder = [
  'user',
  'role',
  'passport',
  'permission',
  // etc.
];

barrels.populate(loadOrder, function(err) {
  if (err) 
    return done(err);

  done();
});
```

But, since `async` creates the records in parallel it's still possible for the `passports` to be created before the `users`, which is, I believe, why I'm getting this error.

I'll leave this matter here for comment a while longer, and then open a PR with the proposed change.

**Comment by stebl** [comment]
You can also do something like this, if you need a workaround; although, I think in this case I'd prefer barrels to follow the given array order.  

```javascript
var loadOrder = [
  ['user'],
  ['role', 'passport', 'permission'],
];

async.mapSeries(loadOrder, function(order, cb) {
  barrels.populate(order, cb);
}, done);

```

**Comment by bredikhin** [comment]
Thank you guys for spotting this and to @marnusw for the fix. Now there's #40 if someone wanna contribute as well. It should be simple, like five lines or something. We'll cut a new release after that.
